.github/workflows/generate-initial-checksums.yml
In this PR:
* Removed the `committed-checksum-tag` input as it is not used. 
* Updated `committed-checksum-location` default
=> Removed input for tagging intital checksum

.github/workflows/pr-1-ci.yml, .gitignore, CONTRIBUTING.md
In this PR:
* Added a new job that will check that the source branch matches `dev-<config>` and the target branch matches `release-<config>`, with both `<config>`s matching. This is so we can have deploy to GitHub Environments that are protected by only allowing runs from protected branches. 
* Added more notes to the CONTRIBUTING.md
Closes #20
=> pr-1-ci.yml: Added prerequisite job to check PR branch names

.github/workflows/call-pr-1-ci.yml, .github/workflows/call-pr-3-bump-tag.yml, .github/workflows/pr-1-ci.yml, .github/workflows/pr-3-bump-tag.yml, CONTRIBUTING.md, README.md
Adding workflows to simplify future updates to CI on config branches. 
In this PR:
* Created `call-*.yml` workflows for `pr-1-ci.yml` and `pr-3-bump-tag.yml`. These workflows simply call their associated workflows that are on the main branch. 
* Updated triggers for `pr-1-ci.yml` and `pr-3-bump-tag.yml` to be `on.workflow_call`
* Updated info in `CONTRIBUTING.md` regarding how to create new config branches from scratch
* Updated `README.md` by adding a link to the above
Closes #24
=> CI Propagation

config/released-configs.json
`released-configs.json` now uses correct, existing config tag (`release-1deg_jra55_ryf-1.0` instead of `release-1deg_jra55_ryf-1.0.0`.
Closes #21
=> Update scheduled release config tag check

.github/workflows/schedule-1-ci.yml, .github/workflows/schedule-2-start.yml
See failling run here: https://github.com/ACCESS-NRI/access-om2-configs/actions/runs/8415375297/job/23040581361#step:3:339
For Scheduled checks, we still required the `permissions.checks: write` even if we a not doing a pull request. 
This PR:
* Gives `permissions.checks:write` to both the overall `schedule-2-start.yml` reusable workflow and the job inside it (`check-checksum`)
=> Give `permissions.checks:write` to Scheduled Checks

.github/workflows/schedule-2-start.yml
See failed run: https://github.com/ACCESS-NRI/access-om2-configs/actions/runs/8428361335/job/23080831075#step:4:4
I incorrectly compare a string with a number (`[ "0" > 0 ]`), which will always be true and set off the failure notifier. 
This PR updates that check to use a POSIX-compilant method for comparing numbers.
=> Properly Compared Number of Failed Tests in JSON for Failure Notifier

test/models/accessom2.py, test/models/model.py, test/test_bit_reproducibility.py
Enable restart reproducibility checksum checks - as detailed in #11 
I've added the marker `checksum` to the restart checksum tests, added a model-specific checksum comparison method (as format of checksums may different depending on the model). 
For access-om2 model, it is basically doing the same check as before, i.e any field and checksum value in the `2-day` model run is in either of the first or second `1 day` model runs. 
I have manually tested it with a `1deg_jra55_ryf` configuration where I’ve just updated the executables paths to point to the corresponding pre-release locations with the fix - [config.yaml used](https://gist.github.com/jo-basevi/734d0c3538ad91a61a985a1bed6a2c2e).  Currently it's failing the `test_bit_repro_historical` test - so the checksums …
=> Add restart reproducibility test into repro CI 

.github/workflows/call-pr-1-ci.yml, .github/workflows/pr-1-ci.yml, .github/workflows/pr-2-confirm.yml, .github/workflows/schedule-2-start.yml, README-DEV.md, test/conftest.py, test/requirements.txt, test/test_access_om2_config.py, test/test_config.py, test/util.py
Add CI checks for checking `config.yaml`, `metadata.yaml` files and simple configuration directory checks, as described in #25.  
Closes #25
TODO:
=> Add pytests and CI for simple configuration checks

CONTRIBUTING.md
An update to the Contribution Guide to include new guidance for using `dev-` branches and explanation of some of the checks and recommended values.
This is to support developers and users when updating model configurations.
=> Contribution guide update

.github/workflows/generate-initial-checksums.yml
This allows users to generate the initial checksums to have a version that is not `1.0` for all initial checksums.
=> generate-initial-checksums.yml: Added user-specifiable tag version

test/test_access_om2_config.py, test/test_config.py
- Test metadata is enabled
- Ensure experiment in config is not defined
- license in metadata set to CC-BY-4.0
- access-om2 sync userscript set to ice concat script
- access-om2 check nominal resolution in metadata
Closes #45
I've assumed the license is a general config check rather than just access-om2 specific?
=> Add extra QA CI checks

test/test_access_om2_config.py
Added check for realm not iterable (when field is empty)
Fixed syntax error in nominal_resolution check. Nominal resolution should be a string, so simplified logic to remove join.
Fixes a syntax error in #51
=> Quick fix for errors in #51

.github/workflows/pr-2-confirm.yml
In this PR:
* pr-2-confirm: Added rocket emoji reaction when `!bump [major|minor]` issued
=> Added `github-actions[bot]` reaction when working on command comment

test/test_access_om2_config.py, test/test_config.py
- Add test for license file and contents, closes #56
- Change access-om2 nominal resolutions to strings, closes #57 
- Change metadata schema url to point to one schema commit -  as schemas should be backwards compatible
=> Update QA pytests

test/conftest.py, test/requirements.txt, test/test_access_om2_config.py
- Read metadata.yaml using ruamel.yaml (as what is used in payu) which errors out on duplicated fields. Closes #80
- Add bgc keyword to list of allowable keywords. Closes #62
- Check for `mpi: true` when using `mppnccombine-fast`. Closes #70
=> Add additional QA checks

.github/workflows/pr-3-bump-tag.yml
Relates to the erroneous running of `pr-3-bump-tag.yml` on initial merge of a `dev-*` branch into `release-*`, see https://github.com/ACCESS-NRI/access-om2-configs/actions/runs/8638862592
In this PR:
* `pr-3-bump-tag.yml`: Added null check
=> Added `pr-3-bump-tag.yml` null check

.github/workflows/pr-1-ci.yml
Pinning model-config-tests as the model-config-tests repository is getting updated/packaged. This is so any CI checks will still run as expected in the meantime.
This is the first part of #109
=> Temporarily pin model-config-tests

config.yaml, manifests/exe.yaml
This PR updates the executables to the [2024.06.0 ACCESS-OM2-BGC release](https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/releases/tag/2024.06.0):
- spack 0.21
- intel-2021.10.0
- Updated [dependency versions](https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/pull/11)
- MOM5 2024.06.27 (includes [WOMBAT ice-to-ocean BGC coupling bug fix](https://github.com/COSIMA/access-om2/issues/282))
=> Update exes to latest release: `025deg_jra55_ryf_bgc`

config.yaml, manifests/exe.yaml
This PR updates the executables to the [2024.07.0 ACCESS-OM2-BGC release](https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/releases/tag/2024.07.0):
- spack 0.22
- MOM5 2024.06.27 (includes [WOMBAT ice-to-ocean BGC coupling bug fix](https://github.com/COSIMA/access-om2/issues/282))
=> Update exes to latest release: `025deg_jra55_iaf_bgc`

.github/workflows/generate-initial-checksums.yml, README-DEV.md, config/ci.json
In this PR:
* Updated `config/ci.json` schema to `2-0-0` - see https://github.com/ACCESS-NRI/schema/pull/35 NOTE: the validation CI will fail until this is merged
* Added global default `payu-version` `1.1.4`
Updated repo settings:
* Added `vars.MODULE_LOCATION` and `vars.PRERELEASE_MODULE_LOCATION`. See https://github.com/ACCESS-NRI/access-om2-configs/settings/environments
* Update `vars.CONFIG_CI_SCHEMA_VERSION` to `2-0-0`. See https://github.com/ACCESS-NRI/access-om2-configs/settings/variables/actions
References ACCESS-NRI/model-config-tests#37
=> `config/ci.json`: Added global default `payu-version` `1.1.4`

config/ci.json
In this PR:
* Update the global `payu-version` from `1.1.4` to `1.1.5` because we are deleting `1.1.4` from Gadi to recover `inodes`
=> Global `payu-version` to `1.1.5`

.github/workflows/ci.yml
In this PR:
- Added `on.create` trigger from https://github.com/ACCESS-NRI/model-configs-template/commit/a1988f076af334d23da3e903b490e6a24f0421bf (from ACCESS-NRI/model-configs-template#3)
NOTE: We only have to add this CI to `main` (and not other `dev-*`/`release-*` branches) because only future configurations (which are based on `ci.yml` from `main`) will require this feature. 
References ACCESS-NRI/model-config-tests#58
=> Added `on.create` Trigger

config/ci.json
References #158
Closes #161
Closes #160
Closes #157
Closes #154
Closes #149
Closes #145
Closes #144
Closes #138
Closes #135
Closes #113
Closes #112
We have been constantly scheduled testing a Config Tag that is known to be not restart-reproducible with itself.
In this PR:
- Remove the `release-1deg_jra55_iaf_bgc-2.0` Scheduled Config Tag as it is known to be unreproducible - see https://github.com/ACCESS-NRI/access-om2-configs/pull/132#issuecomment-2219707510
- Add the later `release-1deg_jra55_iaf_bgc-3.0` which incorporates this fix https://github.com/ACCESS-NRI/access-om2-configs/pull/132
=> Remove Known Unreproducible Scheduled BGC Config Tag `iaf_bgc-2.0`, Add Post-Fix Config Tag `iaf_bgc-3.0`

config/ci.json
Closes #163
The config tag being removed isn't restart reproducible, so we shouldn't test it - it will have different answers every time. Once this is fixed (generic tracer support implemented into ACCESS-OM2) we can add `*_bgc` config tags back to scheduled testing. Thanks @dougiesquire for illuminating the matter! :smile: 
In this PR:
* Remove `release-1deg_jra55_iaf_bgc-3.0` from scheduled testing, because it is not restart reproducible anyway.
=> Remove `release-1deg_jra55_iaf_bgc-3.0` from scheduled testing due to non-reproducibility

.github/workflows/generate-initial-checksums.yml
References ACCESS-NRI/access-esm1.6-configs#73
Similar to the linked issue, a later workflow requires `permissions.checks: write` but we don't give that in the caller. Now we do!
* Give `repro-ci` `permissions.checks: write`
=> Add checks: write permission

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-025deg_jra55_ryf_bgc to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-025deg_jra55_iaf_bgc to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-01deg_jra55_ryf_bgc to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-1deg_jra55_ryf_bgc to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-1deg_jra55_ryf to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-01deg_jra55_ryf to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-025deg_jra55_ryf to pass latest QA tests

config.yaml, manifests/input.yaml, metadata.yaml
=> Update dev-025deg_jra55_iaf to pass latest QA tests
